export interface CountryCode {
    name: string;
    iso2: string;
    dialCode: string; // without +, e.g., "1"
    flag: string; // emoji
}

export const COUNTRY_CODES: CountryCode[] = [
    { name: "United States", iso2: "US", dialCode: "1", flag: "🇺🇸" },
    { name: "Canada", iso2: "CA", dialCode: "1", flag: "🇨🇦" },
    { name: "United Kingdom", iso2: "GB", dialCode: "44", flag: "🇬🇧" },
    { name: "Indonesia", iso2: "ID", dialCode: "62", flag: "🇮🇩" },
    { name: "India", iso2: "IN", dialCode: "91", flag: "🇮🇳" },
    { name: "Australia", iso2: "AU", dialCode: "61", flag: "🇦🇺" },
    { name: "New Zealand", iso2: "NZ", dialCode: "64", flag: "🇳🇿" },
    { name: "Singapore", iso2: "SG", dialCode: "65", flag: "🇸🇬" },
    { name: "Malaysia", iso2: "MY", dialCode: "60", flag: "🇲🇾" },
    { name: "Philippines", iso2: "PH", dialCode: "63", flag: "🇵🇭" },
    { name: "Vietnam", iso2: "VN", dialCode: "84", flag: "🇻🇳" },
    { name: "Thailand", iso2: "TH", dialCode: "66", flag: "🇹🇭" },
    { name: "China", iso2: "CN", dialCode: "86", flag: "🇨🇳" },
    { name: "Hong Kong", iso2: "HK", dialCode: "852", flag: "🇭🇰" },
    { name: "Taiwan", iso2: "TW", dialCode: "886", flag: "🇹🇼" },
    { name: "Japan", iso2: "JP", dialCode: "81", flag: "🇯🇵" },
    { name: "South Korea", iso2: "KR", dialCode: "82", flag: "🇰🇷" },
    { name: "Germany", iso2: "DE", dialCode: "49", flag: "🇩🇪" },
    { name: "France", iso2: "FR", dialCode: "33", flag: "🇫🇷" },
    { name: "Spain", iso2: "ES", dialCode: "34", flag: "🇪🇸" },
    { name: "Italy", iso2: "IT", dialCode: "39", flag: "🇮🇹" },
    { name: "Netherlands", iso2: "NL", dialCode: "31", flag: "🇳🇱" },
    { name: "Belgium", iso2: "BE", dialCode: "32", flag: "🇧🇪" },
    { name: "Sweden", iso2: "SE", dialCode: "46", flag: "🇸🇪" },
    { name: "Norway", iso2: "NO", dialCode: "47", flag: "🇳🇴" },
    { name: "Denmark", iso2: "DK", dialCode: "45", flag: "🇩🇰" },
    { name: "Finland", iso2: "FI", dialCode: "358", flag: "🇫🇮" },
    { name: "Ireland", iso2: "IE", dialCode: "353", flag: "🇮🇪" },
    { name: "Portugal", iso2: "PT", dialCode: "351", flag: "🇵🇹" },
    { name: "Greece", iso2: "GR", dialCode: "30", flag: "🇬🇷" },
    { name: "Poland", iso2: "PL", dialCode: "48", flag: "🇵🇱" },
    { name: "Czechia", iso2: "CZ", dialCode: "420", flag: "🇨🇿" },
    { name: "Austria", iso2: "AT", dialCode: "43", flag: "🇦🇹" },
    { name: "Switzerland", iso2: "CH", dialCode: "41", flag: "🇨🇭" },
    { name: "Russia", iso2: "RU", dialCode: "7", flag: "🇷🇺" },
    { name: "Turkey", iso2: "TR", dialCode: "90", flag: "🇹🇷" },
    { name: "Saudi Arabia", iso2: "SA", dialCode: "966", flag: "🇸🇦" },
    { name: "United Arab Emirates", iso2: "AE", dialCode: "971", flag: "🇦🇪" },
    { name: "Qatar", iso2: "QA", dialCode: "974", flag: "🇶🇦" },
    { name: "Bahrain", iso2: "BH", dialCode: "973", flag: "🇧🇭" },
    { name: "Kuwait", iso2: "KW", dialCode: "965", flag: "🇰🇼" },
    { name: "Pakistan", iso2: "PK", dialCode: "92", flag: "🇵🇰" },
    { name: "Bangladesh", iso2: "BD", dialCode: "880", flag: "🇧🇩" },
    { name: "Sri Lanka", iso2: "LK", dialCode: "94", flag: "🇱🇰" },
    { name: "Nepal", iso2: "NP", dialCode: "977", flag: "🇳🇵" },
    { name: "Nigeria", iso2: "NG", dialCode: "234", flag: "🇳🇬" },
    { name: "Kenya", iso2: "KE", dialCode: "254", flag: "🇰🇪" },
    { name: "South Africa", iso2: "ZA", dialCode: "27", flag: "🇿🇦" },
    { name: "Egypt", iso2: "EG", dialCode: "20", flag: "🇪🇬" },
    { name: "Israel", iso2: "IL", dialCode: "972", flag: "🇮🇱" },
    { name: "Mexico", iso2: "MX", dialCode: "52", flag: "🇲🇽" },
    { name: "Brazil", iso2: "BR", dialCode: "55", flag: "🇧🇷" },
    { name: "Argentina", iso2: "AR", dialCode: "54", flag: "🇦🇷" },
    { name: "Chile", iso2: "CL", dialCode: "56", flag: "🇨🇱" },
    { name: "Colombia", iso2: "CO", dialCode: "57", flag: "🇨🇴" },
    { name: "Peru", iso2: "PE", dialCode: "51", flag: "🇵🇪" },
    { name: "Uruguay", iso2: "UY", dialCode: "598", flag: "🇺🇾" },
    { name: "Paraguay", iso2: "PY", dialCode: "595", flag: "🇵🇾" },
    { name: "Bolivia", iso2: "BO", dialCode: "591", flag: "🇧🇴" },
    { name: "Venezuela", iso2: "VE", dialCode: "58", flag: "🇻🇪" },
    { name: "Costa Rica", iso2: "CR", dialCode: "506", flag: "🇨🇷" },
    { name: "Panama", iso2: "PA", dialCode: "507", flag: "🇵🇦" },
    { name: "Dominican Republic", iso2: "DO", dialCode: "1", flag: "🇩🇴" },
    { name: "Puerto Rico", iso2: "PR", dialCode: "1", flag: "🇵🇷" },
    { name: "Jamaica", iso2: "JM", dialCode: "1", flag: "🇯🇲" },
    { name: "Trinidad and Tobago", iso2: "TT", dialCode: "1", flag: "🇹🇹" },
    { name: "Romania", iso2: "RO", dialCode: "40", flag: "🇷🇴" },
    { name: "Bulgaria", iso2: "BG", dialCode: "359", flag: "🇧🇬" },
    { name: "Hungary", iso2: "HU", dialCode: "36", flag: "🇭🇺" },
    { name: "Ukraine", iso2: "UA", dialCode: "380", flag: "🇺🇦" },
    { name: "Belarus", iso2: "BY", dialCode: "375", flag: "🇧🇾" },
    { name: "Georgia", iso2: "GE", dialCode: "995", flag: "🇬🇪" },
    { name: "Armenia", iso2: "AM", dialCode: "374", flag: "🇦🇲" },
    { name: "Azerbaijan", iso2: "AZ", dialCode: "994", flag: "🇦🇿" },
    { name: "Kazakhstan", iso2: "KZ", dialCode: "7", flag: "🇰🇿" },
    { name: "Uzbekistan", iso2: "UZ", dialCode: "998", flag: "🇺🇿" },
    { name: "United Republic of Tanzania", iso2: "TZ", dialCode: "255", flag: "🇹🇿" },
    { name: "Ethiopia", iso2: "ET", dialCode: "251", flag: "🇪🇹" },
    { name: "Ghana", iso2: "GH", dialCode: "233", flag: "🇬🇭" },
    { name: "Morocco", iso2: "MA", dialCode: "212", flag: "🇲🇦" },
    { name: "Algeria", iso2: "DZ", dialCode: "213", flag: "🇩🇿" },
    { name: "Tunisia", iso2: "TN", dialCode: "216", flag: "🇹🇳" },
    { name: "Zimbabwe", iso2: "ZW", dialCode: "263", flag: "🇿🇼" },
    { name: "Zambia", iso2: "ZM", dialCode: "260", flag: "🇿🇲" },
    { name: "Uganda", iso2: "UG", dialCode: "256", flag: "🇺🇬" },
    { name: "Cameroon", iso2: "CM", dialCode: "237", flag: "🇨🇲" },
    { name: "Ivory Coast", iso2: "CI", dialCode: "225", flag: "🇨🇮" },
    { name: "Senegal", iso2: "SN", dialCode: "221", flag: "🇸🇳" },
    { name: "Togo", iso2: "TG", dialCode: "228", flag: "🇹🇬" },
    { name: "Benin", iso2: "BJ", dialCode: "229", flag: "🇧🇯" },
    { name: "Rwanda", iso2: "RW", dialCode: "250", flag: "🇷🇼" },
    { name: "Botswana", iso2: "BW", dialCode: "267", flag: "🇧🇼" },
    { name: "Namibia", iso2: "NA", dialCode: "264", flag: "🇳🇦" },
    { name: "Mozambique", iso2: "MZ", dialCode: "258", flag: "🇲🇿" },
    { name: "Angola", iso2: "AO", dialCode: "244", flag: "🇦🇴" },
    { name: "Ecuador", iso2: "EC", dialCode: "593", flag: "🇪🇨" },
    { name: "Guatemala", iso2: "GT", dialCode: "502", flag: "🇬🇹" },
    { name: "Honduras", iso2: "HN", dialCode: "504", flag: "🇭🇳" },
    { name: "El Salvador", iso2: "SV", dialCode: "503", flag: "🇸🇻" },
    { name: "Nicaragua", iso2: "NI", dialCode: "505", flag: "🇳🇮" },
    { name: "Cuba", iso2: "CU", dialCode: "53", flag: "🇨🇺" },
    { name: "Haiti", iso2: "HT", dialCode: "509", flag: "🇭🇹" },
    { name: "Dominica", iso2: "DM", dialCode: "1", flag: "🇩🇲" },
    { name: "Barbados", iso2: "BB", dialCode: "1", flag: "🇧🇧" },
    { name: "Bahamas", iso2: "BS", dialCode: "1", flag: "🇧🇸" }
];

export function findCountryByIso(iso2: string): CountryCode | undefined {
    return COUNTRY_CODES.find(c => c.iso2.toLowerCase() === iso2.toLowerCase());
}



